<a href="https://colab.research.google.com/github/AndreassOlsson/Basic-AI-ML-exploration/blob/main/datahandling_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Uploading, streaming and sampling data

### Uploading small amounts of data into memory

In [ ]:
with open('file_name.txt', 'r') as open_file: # 'r' represents read mode
    print('file_name.txt content:\n' + open_file.read())

### Uploadning large amounts of data into memory

In [ ]:
with open('file_name.txt', 'r') as open_file: 
    for observation in open_file:
        print('Reading Data: ' + observation)

FileNotFoundError: [Errno 2] No such file or directory: 'file_name.txt'

### Sampling image data

In [ ]:
import matplotlib.image as img
import matplotlib.pyplot as plt
%matplotlib inline

image = img.imread("file_name.jpg")
print(image.shape) # (Horizontal, vertical, depth)
print(image.size) # Product of image.shape
plt.imshow(image)
plt.show()

### Sampling data by row number

Data streaming obtains all the records from a data source. If you don´t need all the records, save time by simply sampling the data, for example by only viewing every fifth item.

In [ ]:
n = 2 # View every second item
with open('file_name.txt', 'r') as open_file: 
    for j, observation in enumerate(open_file): 
        if j % n==0: 
            print('Reading Line: ' + str(j) + 
                 ' Content:' + observation)

### Random sampling

In [ ]:
from random import random
sample_size = 0.25 # Will display 25% of information
with open('file_name.txt', 'r') as open_file:
    for j, observation in enumerate(open_file):
        if random()<=sample_size:
            print('Reading Line: ' + str(j) + 
                 ' Content:' + observation)

# Data input isn´t intelligent

A problem with using native python techniques is that the input isn´t intelligent. For example, python reads a header as yet more data to process and not a header. You can´t easily select a particular column of data. The Pandas library used in the sections that follow makes it much easier to read and understand flat-file data. Classes and methods in the Pandas library interpret (parse) the flat-tile data to make it easier to manipulate.

The least formatted and therefor easiest-to-read flat-file format is the text file. However, a text file also treats all data as strings, so you often have to convert numeric data to into other forms. A comma-separated calue (CSV) file provides more formatting and more information, but it requires a little more effort to read. At the high end of flat-file formatting are custom data formats, such as an Excel file, which contains extensive formatting and could include multiple datasets in a single file.

The following sections describe these three levels of flat-file datasets and show how to use them. These sections assume that the file structures the data in some way. For example, the CSV file uses commas to seperate data fields. An Excel file uses a complex method to seperate data fields and to provide a wealth of information about each field. You can work with unstructured data as well, but working with structured is easier because you know where each field begins and ends.

### Reading from a text file

Text files can use a variety of storage formats. However, a common format is to have a header line that documents the purpose of each field, followed by another line for each record in the file. The file separates the fields using tabs. 

Pandas library holds a set of parsers, code used to read individual bits of data and determine the purpose of each bit according to the format of the entire file. Using the right parser is essential, if you want to make any sence of file content. One example is using the 'read_tabel()' method.

In [ ]:
import pandas as pd
table = pd.io.parsers.read_table('file_name.txt')
print(table)
# You can adjust how the parser interprets the input file but the default settings works well.

### Reading CSV delimited format

The structure for a CSV file can look something like this:
1. A header defines each of the fields
2. Fields are separeted by commas
3. Records are separeted by linefeeds
4. Stings are enclosed in double quotes
5. Integers and real numbers appear without double quotes
    
You can use an application such as Excel to create a CSV formatted presentation.

In [ ]:
import pandas as pd
file = pd.io.parsers.read_csv('file_name.csv')
X = file[['header']] # Could be 'age', 'sex' etc.
# X = file[['header']].values (turns output into list)
print(X)

FileNotFoundError: [Errno 2] File file_name.csv does not exist: 'file_name.csv'

### Reading Excel and other microsoft files

In [ ]:
import pandas as pd
xls = pd.ExcelFile("file_name.xls")
observations = xls.parse('Sheet1', index_col=None, # Generate an index
                       na_values=['NA'])
print(observations)

In [ ]:
import pandas as pd

observations = pd.read_excel("file_name.xls", 'Sheet1', index_col=None, na_values=['NA'])

### Sending data in unstructured file form

Unstructured data files consist of a series of bits. The file does not on its own separate the bits and you can´t simply look into the file and see any structure. Therefor, unstructured data rely on the file user to know how to interpret the data. For example, a picture could consist of three 32-bit fields, which is up to you to find out. Here is an example of working with unstructured data in the form of a picture.

In [ ]:
from skimage.io import imread
from skimage.transform import resize
from matplotlib import pyplot as plt
import matplotlib.cm as cm

example_file = ("gädda.jpg")
image = imread(example_file, as_gray=True)
plt.imshow(image, cmap=cm.gray)
plt.show()

In [ ]:
print("data type: %s, shape: %s" %
     (type(image), image.shape))

In [ ]:
image2 = image[50:1000,50:1000]
plt.imshow(image2, cmap=cm.gray)
plt.show()

In [ ]:
image3 = resize(image, (529//2,705//2), mode='symmetric')
plt.imshow(image3, cmap=cm.gray)
plt.show()
print("data type: %s, shape: %s" %
     (type(image3), image3.shape))

In [ ]:
image_row = image3.flatten()
print("data type: %s, shape: %s" %
     (type(image_row), image_row.shape))
print("(264*352)")

### Creating a connection to a sql database

In [ ]:
from sqlalchemy import create_engine
engine = create_engine('sqlite:///:memory:')

After you have accesse to an engine, you can use the engine to performe tasks specific to that DBMS (Database Management System). The output of a read method is always a DataFrame object that contains the requested data. To write data, you must create a DataFrame object or use an existing DataFrame object. You normally use these methods to perform most tasks:

In [ ]:
read_sql_tabel() 
# Reads data from a SQL table to a DatFrame object
read_sql_query()
# Reads data from a database using a SQL query to a DataFrame object
read_sql()
# Reads data from either a SQL table or query to a DataFrame object
DataFrame.to_sql()
# Writes the content of a DataFrame object to the specified tables in the database

### NoSQL databases

The process of using Not only SQL (NoSQL) databases:
1. Import required database engine functionality
2. Create a database engine
3. Make any required queries using the database engine and the functionality supported by the DBMS.

Discover more about working with datasets at sqlalchemy.org 

In [ ]:
import pymongo
import pandas as pd
from pymongo import Connection
connection = Connection()
db = connection.database_name
input_data = db.collection_name
data = pd.DataFrame(list(input_data.find()))

### XML

In [ ]:
from IPython.display import Image
Image("XML.jpg")

FileNotFoundError: No such file or directory: 'XML.jpg'

FileNotFoundError: No such file or directory: 'XML.jpg'

<IPython.core.display.Image object>

In [ ]:
from lxml import objectify
import pandas as pd

xml = objectify.parse(open('XMLData.xml'))
root = xml.getroot()

df = pd.DataFrame(columns=['customer_id', 'first_name', 'last_name', 'email'])
# For the example image

for i in range(0,5):
    obj = root.getchildren()[i].getchildren()
    row = dict(zip(['customer_id', 'first_name', 'last_name', 'email'],
                   [obj[0].text, obj[1].text,
                    obj[2].text, obj[3].text]))
    row_s = pd.Series(row)
    row_s.name = i
    df = df.append(row_s)
    
# Search for duplicates
search = df.DataFrame.duplicated(df)
print(df)
print(search[search == True])

# Remove duplicates
print(df.drop_duplicates())

FileNotFoundError: [Errno 2] No such file or directory: 'XMLData.xml'

### Preparation

1. Get the data
2. Aggregate the data
3. Create data subsets
4. Clean the data
5. Develop a single dataset by merging various datasets together

### Creating a data map and a data plan

You need to be aware of how your data looks statisticly. A data map is an overview of the dataset. You use it to spot potential problems in your data such as:

1. Redundant variables
2. Possible errors
3. Missing values
4. Variable transformations

Cheching for these problems goes into a data plan, which is a list of tasks that you have to preform to ensure the integrity of your data. The following example shows a data map, A, with two datasets, B and C.

In [ ]:
import pandas as pd
pd.set_option('display.width', 55)

df = pd.DataFrame({'A': [0,0,0,0,0,1,1],
                   'B': [1,2,3,5,4,2,5],
                   'C': [5,3,4,1,1,2,3]})

a_group_desc = df.groupby('A').describe()
#print(a_group_desc)

# stacked = a_group_desc.stack()
# print(stacked)

print(a_group_desc.loc[:,(slice(None),['count','mean']),])


### Creating categorical variables

In data science, a categorical value is one that has a specific value from a limited selection of values. The number of values is usually fixed. Many developer will know categorical values by the moniker enumerations. Each of the potential values that a categoriacl variable can assume is called a level.

Let´s say that you have an variable to express the color of a car. The computer interpret it as a numerical value, so normally when you print the color of a car, the value of the color is returned. If you use pandas.DataFrame, you can still use the symbolic value (blue, red, green), even tough the computer sees it as a numeric value. Sometimes you need to combine and rename these named values to create new symbols. 

Symbolic variables are just a convenient way of representing and storing qualitiative data. 

Some algorithms, such as trees and ensembles of three, can work directly with numerical values behind the symbols, while other require binary variables. This can be algorithms such as linear or logistic regression and SVM.

In [ ]:
import pandas as pd

car_colors = pd.Series(['Blue', 'Red', 'Green'],
                      dtype='category')

car_data = pd.Series(
    pd.Categorical(
        ['Yellow', 'Green', 'Red', 'Blue', 'Purple'],
                    categories=car_colors, ordered=False))

# Find missing values
find_entries = pd.isnull(car_data)

print(car_colors)
print()
print(car_data)
print()
print(find_entries[find_entries == True])

In [ ]:
import pandas as pd

car_colors = pd.Series(['Blue', 'Red', 'Green'],
                      dtype='category')

car_data = pd.Series(
    pd.Categorical(
        ['Yellow', 'Green', 'Red', 'Blue', 'Purple'],
                    categories=car_colors, ordered=False))

car_colors.cat.categories = ['Purple', 'Yellow', 'Mauve']
car_data.cat.categories = car_colors

print(car_data)

### Combining levels

A particular categorical level might be too small to offer significant data to analysis. Perhaps there are only a few of the values, which may not be enough to create a statistical difference. In this case, combining several small categories might offer better analysis results. The following example shows how to combine categories:

In [ ]:
import pandas as pd

car_colors = pd.Series(['Blue', 'Red', 'Green'],
    dtype='category')
car_data = pd.Series(
    pd.Categorical(
    ['Blue','Green','Red','Green','Red','Green'],
    categories=car_colors, ordered=False))

car_data = car_data.cat.set_categories(
    ['Blue','Red','Green','Blue_Red'])
print(car_data.loc[car_data.isin(['Red'])])
car_data.loc[car_data.isin(['Red'])] = 'Blue_Red'
car_data.loc[car_data.isin(['Blue'])] = 'Blue_Red'
car_data = car_data.cat.set_categories(
    ['Green', 'Blue_Red'])

print()
print(car_data)

2    Red
4    Red
dtype: category
Categories (4, object): ['Blue', 'Red', 'Green', 'Blue_Red']

0    Blue_Red
1       Green
2    Blue_Red
3       Green
4    Blue_Red
5       Green
dtype: category
Categories (2, object): ['Green', 'Blue_Red']


### Date and time

Keep in mind that Excel users can choose to start dates in 1900 or 1904 and the numeric encoding for each is diferent.

In [ ]:
import datetime as dt

now = dt.datetime.now()

print(str(now))
print(now.strftime('%a, %d, %B, %Y'))

In [ ]:
import datetime as dt

now = dt.datetime.now()
timevalue = now + dt.timedelta(hours=2)

print(now.strftime('%a, %d, %B, %Y'))
print(now.strftime('%H:%M:%S'))
print(timevalue.strftime('%H:%M:%S'))

if now < timevalue:
    print(timevalue - now)
else:
    print(now - timevalue)

### Dealing with missing data

In [ ]:
# Finding the missing data
import pandas as pd
import numpy as np

s = pd.Series([1, 2, 3, np.NaN, 5, 6, None])

print(s.isnull())

print()
print(s[s.isnull()])

0    False
1    False
2    False
3     True
4    False
5    False
6     True
dtype: bool

3   NaN
6   NaN
dtype: float64


Handle the missing data by ignoring, filling or removing (drop) it.

In [ ]:
import pandas as pd
import numpy as np

s = pd.Series([1, 2, 3, np.NaN, 5, 6, None])

print(s.fillna(int(s.mean())))
# Fill in the missing values using the mean (medelvärde)
print()
print(s.dropna())
# Drop the missing values

Working with series is straightforward because the dataset is simple. However, when working with a dataframe it is not as simple. You still have the option of dropping the entire row but when a column is sparsely populated, you might want to drop the column instead. Filling in the data also becomes more complicated because you must consider the dataset as a whole, in addition to the needs of the individual feature.

In [ ]:
# Imputing missing data
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer as imputer

s = [[1, 2, 3, np.NaN, 5, 6, None]]

imp = imputer(missing_values=np.nan, strategy='mean')
# mean, median, most_frequent

imp.fit([[1, 2, 3, 4, 5, 6, 7]])

x = pd.Series(imp.transform(s).tolist()[0])

print(x)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    7.0
dtype: float64


### Slicing rows and columns


Slicing a row from a row of 2-D or 3-D data allows you to focus on specific data. In some cases, you might associate rows with cases in a dataset.

In [ ]:
# An example of a 3-D array
x = np.array([[[1,2,3], [4,5,6], [7,8,9]],
             [[11,12,13], [14,15,16], [17,18,19]],
             [[21,22,23], [24,25,26], [27,28,29]]])


# Slice row
print(f"Sliced row: \n {x[1]}")

# Slice column
print(f"\nSliced column: \n {x[:,1]}")

Sliced row: 
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

Sliced column: 
 [[ 4  5  6]
 [14 15 16]
 [24 25 26]]


### Dicing

Dicing means preforming both a slicing of a row and column.

In [ ]:
x = np.array([[[1,2,3], [4,5,6], [7,8,9],],
             [[11,12,13], [14,15,16], [17,18,19],],
             [[21,22,23], [24,25,26], [27,28,29]]])

# Row and column
print(x[1,2])

### Concatenating and transforming

Combine diferent datasets with diferent formats into a single dataset. You also need to keep in mind that the same data can be in diferent forms, for example, age can be both integer or string. For the fields to work together, they must appear as the same type of information. 

You often find a need to combine datasets in various ways or even to add new information for the sake of analysis purposes. The result is a combined dataset that includes either new cases or variables. The following example shows techniques for preforming both tasks. 

### Combining dataframes 

In [ ]:
import pandas as pd

df = pd.DataFrame({'A': [2,3,1],
                   'B': [1,2,3],
                   'C': [5,3,4]})

df1 = pd.DataFrame({'A': [4],
                    'B': [4],
                    'C': [4]})

df = df.append(df1) # concat() 
df = df.reset_index(drop=True)
print(df)

df.loc[df.last_valid_index() + 1] = [5,5,5]
print()
print(df)

df2 = pd.DataFrame({'D': [1, 2, 3, 4, 5]})

df = pd.DataFrame.join(df, df2)
print()
print(df)

### Removing data

In [ ]:
import pandas as pd

df = pd.DataFrame({'A': [2,3,1],
                   'B': [1,2,3],
                   'C': [5,3,4]})

df = df.drop(df.index[1])
print(df)

df = df.drop('B', axis=1)
df = df.drop(2, axis=0)
print()
print(df)

### Sorting and shuffling data order

You sort and shuffle in order to manage data order. This might mess up your results for the purpose of analysis but can be useful for presentation purposes.

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'A': [1,5,2,3,5,6,7],
                'B': [5,3,6,1,5,8,9],
                'C': [7,2,4,6,8,3,3]})

# Sort
df = df.sort_values(by=['A','C'], ascending=[True, True])
df = df.reset_index(drop=False)
print(df)


# Shuffle
index = df.index.tolist()
np.random.shuffle(index)
df = df.loc[df.index[index]]
df = df.reset_index(drop=True)
print()
print(df)

### Aggregating data at any level

Aggregation is the process of combining or grouping data together into a set, bag or list. The data may or may not be alike. However, in most cases, an aggregation function combines several rows together statistically, using algorithms such as average, count, maximum, median, minimum, mode or sum. There are several reasons to aggreagte data:

1. Make it easier to analyse
2. Reduce the ability of anyone to deduce the data of an individual from the dataset for privace and other reasons. 
3. Create a combined data element from one data source that matches a combined data element in another source. 

In [ ]:
import pandas as pd

df = pd.DataFrame({'Map': [0,0,0,1,1,2,2,],
                   'Values': [1,2,3,5,4,2,5]})

df['S'] = df.groupby('Map')['Values'].transform(np.sum)
df['M'] = df.groupby('Map')['Values'].transform(np.mean)
df['V'] = df.groupby('Map')['Values'].transform(np.var)

print(df)

   Map  Values  S    M    V
0    0       1  6  2.0  1.0
1    0       2  6  2.0  1.0
2    0       3  6  2.0  1.0
3    1       5  9  4.5  0.5
4    1       4  9  4.5  0.5
5    2       2  7  3.5  4.5
6    2       5  7  3.5  4.5
